version: "3.9"
   
services:
  db:
    build: 
      context: db_docker
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/opt
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 groundWaterProject.wsgi
    
    volumes:
      - .:/code
      - ./db_data:/opt
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx_docker
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./staticfiles:/opt/staticfiles
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

