# Generated by Django 2.2 on 2021-08-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GwMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.BigIntegerField(blank=True, null=True)),
                ('start', models.CharField(blank=True, max_length=200, null=True)),
                ('end', models.CharField(blank=True, max_length=200, null=True)),
                ('today', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceid', models.CharField(blank=True, max_length=200, null=True)),
                ('enumerator_name', models.CharField(blank=True, max_length=200, null=True)),
                ('select_district', models.CharField(blank=True, max_length=200, null=True)),
                ('geographic_location', models.CharField(blank=True, max_length=200, null=True)),
                ('field_geographic_location_latitude', models.CharField(blank=True, db_column='_geographic_location_latitude', max_length=200, null=True)),
                ('field_geographic_location_longitude', models.CharField(blank=True, db_column='_geographic_location_longitude', max_length=200, null=True)),
                ('field_geographic_location_altitude', models.CharField(blank=True, db_column='_geographic_location_altitude', max_length=200, null=True)),
                ('field_geographic_location_precision', models.CharField(blank=True, db_column='_geographic_location_precision', max_length=200, null=True)),
                ('well_type_field', models.CharField(blank=True, db_column='well_type__', max_length=200, null=True)),
                ('well_no_bd_dw', models.CharField(blank=True, db_column='well_no__bd_dw', max_length=200, null=True)),
                ('well_no_bd_sw', models.CharField(blank=True, db_column='well_no__bd_sw', max_length=200, null=True)),
                ('well_no_bk_dw', models.CharField(blank=True, db_column='well_no__bk_dw', max_length=200, null=True)),
                ('well_no_bk_sw', models.CharField(blank=True, db_column='well_no__bk_sw', max_length=200, null=True)),
                ('measurement_point_cm', models.CharField(blank=True, max_length=200, null=True)),
                ('field_your_mp_is_measurement_point_cm_cm_above_ground_field', models.CharField(blank=True, db_column='_your_mp_is___measurement_point_cm__cm_above_ground__', max_length=200, null=True)),
                ('photo_of_well_use_the_camera_to_take_a_clear_photo_of_the_well', models.CharField(blank=True, db_column='photo_of_well__use_the_camera_to_take_a_clear_photo_of_the_well', max_length=200, null=True)),
                ('measurement_of_tape_at_measurement_point_mp_in_m_field', models.CharField(blank=True, db_column='measurement_of_tape_at_measurement_point__mp___in_m_', max_length=200, null=True)),
                ('measurement_of_wet_point_on_tape_in_m_field', models.CharField(blank=True, db_column='measurement_of_wet_point_on_tape__in_m_', max_length=200, null=True)),
                ('gw_level_from_mp', models.CharField(blank=True, max_length=200, null=True)),
                ('mp_in_m', models.CharField(blank=True, max_length=200, null=True)),
                ('gw_level', models.CharField(blank=True, max_length=200, null=True)),
                ('field_the_water_level_is_gw_level_m_below_ground_field', models.CharField(blank=True, db_column='_the_water_level_is___gw_level__m_below_ground_', max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('audio_notes_use_the_camera_s_microphone_to_record_any_notes', models.CharField(blank=True, db_column='audio_notes__use_the_camera_s_microphone_to_record_any_notes', max_length=200, null=True)),
                ('field_version_field', models.CharField(blank=True, db_column='__version__', max_length=200, null=True)),
                ('field_id', models.IntegerField(blank=True, db_column='_id', null=True)),
                ('field_uuid', models.CharField(blank=True, db_column='_uuid', max_length=200, null=True)),
                ('field_submission_time', models.CharField(blank=True, db_column='_submission_time', max_length=200, null=True)),
                ('field_validation_status', models.CharField(blank=True, db_column='_validation_status', max_length=200, null=True)),
                ('field_notes', models.CharField(blank=True, db_column='_notes', max_length=200, null=True)),
                ('field_status', models.CharField(blank=True, db_column='_status', max_length=200, null=True)),
                ('field_submitted_by', models.CharField(blank=True, db_column='_submitted_by', max_length=200, null=True)),
                ('field_tags', models.CharField(blank=True, db_column='_tags', max_length=200, null=True)),
                ('field_index', models.IntegerField(blank=True, db_column='_index', null=True)),
            ],
            options={
                'db_table': 'gw_monitoring',
                'managed': False,
            },
        ),
    ]
