# Generated by Django 2.2 on 2021-08-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gwmonitoring',
            options={'managed': True},
        ),
    ]
