# Generated by Django 2.2 on 2021-08-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0004_auto_20210825_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='GwLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_number', models.CharField(blank=True, max_length=100, null=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'graound_water_locations',
                'managed': True,
            },
        ),
    ]
