# Generated by Django 2.2 on 2021-08-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0006_welltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwlocations',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waterApp.WellType'),
        ),
    ]
