# Generated by Django 2.2 on 2021-09-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0007_gwlocations_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwmonitoring',
            name='fid',
        ),
        migrations.AlterField(
            model_name='gwmonitoring',
            name='id',
            field=models.BigIntegerField(default=3333, primary_key=True, serialize=False),
        ),
    ]
