# Generated by Django 2.2 on 2021-09-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0008_auto_20210911_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwmonitoring',
            name='id',
            field=models.BigAutoField(default=3333, primary_key=True, serialize=False),
        ),
    ]
