# Generated by Django 2.2 on 2021-09-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0010_auto_20210911_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwmonitoring',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
