# Generated by Django 2.2 on 2021-09-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0011_auto_20210911_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='GwLocationsData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('well_number', models.CharField(blank=True, max_length=100, null=True)),
                ('well_num', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waterApp.WellType')),
            ],
        ),
    ]
