# Generated by Django 2.2 on 2021-09-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0012_gwlocationsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwlocationsdata',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
