# Generated by Django 2.2 on 2021-09-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0013_gwlocationsdata_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GwMonitoringKobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('well_type', models.CharField(blank=True, max_length=150, null=True)),
                ('measurement_point_cm', models.IntegerField(blank=True, null=True)),
                ('measurement_of_wet_point_on_tape_in_m_field', models.CharField(blank=True, db_column='measurement_of_wet_point_on_tape__in_m_', max_length=150, null=True)),
                ('gw_level_from_mp', models.FloatField(blank=True, null=True)),
                ('mp_in_m', models.FloatField(blank=True, null=True)),
                ('gw_level', models.FloatField(blank=True, null=True)),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('well_num', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'gw_monitoring_kobo',
                'managed': False,
            },
        ),
    ]
