# Generated by Django 2.2 on 2021-09-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0014_gwmonitoringkobo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gwmonitoringkobo',
            options={'managed': True},
        ),
    ]
