# Generated by Django 2.2 on 2021-09-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0015_auto_20210914_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwmonitoringkobo',
            name='id',
        ),
        migrations.AlterField(
            model_name='gwmonitoringkobo',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='gwmonitoringkobo',
            name='fid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
