# Generated by Django 2.2 on 2021-09-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0016_auto_20210914_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineLoggerData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('water_level', models.FloatField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
