# Generated by Django 2.2 on 2021-09-21 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0017_offlineloggerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('well_number', models.CharField(blank=True, max_length=100, null=True)),
                ('well_num', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('water_level', models.FloatField(blank=True, null=True)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waterApp.WellType')),
            ],
        ),
    ]
