# Generated by Django 2.2 on 2022-03-03 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterApp', '0018_historicaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwlocationsdata',
            name='well_num',
            field=models.CharField(default='well-00', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gwmonitoringkobo',
            name='well_num',
            field=models.ForeignKey(db_column='well_num', default='well-00', on_delete=django.db.models.deletion.CASCADE, to='waterApp.GwLocationsData', to_field='well_num'),
        ),
    ]
